### ISSUE TITLE
[Issue] Player can still die from ACE Medical Simulation while AFK

### ISSUE THREAD

**Issue by L-McKendrick** [Soliders-in-Arms-Arma-3-Group/SIA-Mission-Framework.VR#1]

**Comment by L-McKendrick** [comment]
Will have to wait for next ACE update for option: https://github.com/acemod/ACE3/pull/7944/files

**Comment by L-McKendrick** [comment]
Requires additional rewriting of AFK script, must be called in unschedule environment. See https://ace3public.slack.com/archives/C04CEBRFZ/p1635236114189500

**Comment by SiegeToaster** [comment]
Commit 4535bada73af761d301bc734053e5849814be620 from #12 should resolve this issue.
