### ISSUE TITLE
Exit AFK menu can be closed from other dialogs closing it.

### ISSUE THREAD

**Issue by SiegeToaster** [Soliders-in-Arms-Arma-3-Group/SIA-Mission-Framework.VR#13]
To reproduce, go AFK, wait for exit AFK menu to appear, and open the self ace interact menu.

Need to find a way to detect if dialog is still open, and if it isn't, exit AFK.

**Comment by L-McKendrick** [comment]
Thanks, someone had said this happened to them a while ago but didn't know why. Now I have a repro [😍](https://emojipedia.org/smiling-face-with-heart-eyes/)

**Comment by SiegeToaster** [comment]
Possible solution: https://community.bistudio.com/wiki/User_Interface_Event_Handlers#onUnload
Add this to the dialogAFK class, code should just spawn the display again.
