### ISSUE TITLE
Further OCAP2 integration

### ISSUE THREAD

**Issue by L-McKendrick** [Soliders-in-Arms-Arma-3-Group/SIA-Mission-Framework.VR#29]
On the mission end have the OCAP2 upload with the correct tag with [`call ocap_fnc_exportData;`](https://github.com/OCAP2/OCAP#usage)

Requires the day of the week, which can be found with
https://forums.bohemia.net/forums/topic/188326-return-day-of-week-from-date/
http://killzonekid.com/arma-extension-real_date-dll-v3-0/

Also add [custom game events](https://github.com/OCAP2/OCAP/wiki/Custom-Game-Events) for mission start 

- [x] Get day of week to determine side/main op
- [x] Call `call ocap_fnc_exportData;` on mission end
- [ ] Implement [custom game events](https://github.com/OCAP2/OCAP/wiki/Custom-Game-Events)

**Comment by SiegeToaster** [comment]
21b82373df6074077ff5c63a2aa1c64df0a9e24c calls ocap_fnc_exportData on mission end and uses the real_date extension to determine side/main/ZGM OP
